### ISSUE TITLE
angeleIndex angleScore angleTime字段含义。

### ISSUE THREAD

**Issue by brokensword2018** [RapidAI/RapidOcrNcnn#7]
struct TextBlock {
    std::vector<cv::Point> boxPoint;
    float boxScore;
    int angleIndex;
    float angleScore;
    double angleTime;
    std::string text;
    std::vector<float> charScores;
    double crnnTime;
    double blockTime;
};

大佬， TextBlock结构体中，三个angle相关的字段含义表示什么呢。没有找到相关文档说明。

**Comment by benjaminwan** [comment]
angleIndex=0代表此行是正的，angleIndex=1代表此行是反的
angleScore是结果的置信度
angleTime是所花的时间

**Comment by brokensword2018** [comment]
感谢
